version: "3.0"
services:
  db:
    container_name: postgres-unwrapped-osm
    image: postgis/postgis
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: openstreetmap
      POSTGRES_EXTENSION: hstore
    volumes:
      - D:\\russia-latest.osm.pbf:/data/russia-latest.osm.pbf