version: "3.0"
services:
  db1:
    container_name: postgres-routing-osm
    image: postgis/postgis
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: routeosm
      POSTGRES_EXTENSION: hstore

  db2:
    container_name: postgres-gate-osm
    image: library/postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateosm
