version: "3.0"
services:
  db:
    container_name: postgis-osm
    image: postgis/postgis:16-master
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: osm
      POSTGRES_EXTENSION: hstore