CREATE SEQUENCE IF NOT EXISTS users_sequence START WITH 1 INCREMENT BY 1;

CREATE TABLE city
(
    city_id    BIGINT NOT NULL,
    city_name  VARCHAR(255),
    country_id BIGINT,
    CONSTRAINT pk_city PRIMARY KEY (city_id)
);

CREATE TABLE country
(
    country_id       BIGINT       NOT NULL,
    country_name     VARCHAR(255) NOT NULL,
    iso3166_1        VARCHAR(255),
    iso3166_1_alpha2 VARCHAR(255),
    CONSTRAINT pk_country PRIMARY KEY (country_id)
);

CREATE TABLE line_string
(
    id       BIGINT NOT NULL,
    route_id BIGINT,
    geom     BYTEA,
    CONSTRAINT pk_line_string PRIMARY KEY (id)
);

CREATE TABLE local_places_bus_stop
(
    bus_stop_id BIGINT NOT NULL,
    lon         DOUBLE PRECISION,
    lat         DOUBLE PRECISION,
    name        VARCHAR(255),
    CONSTRAINT pk_local_places_bus_stop PRIMARY KEY (bus_stop_id)
);

CREATE TABLE local_places_lift_gates
(
    gates_id      BIGINT NOT NULL,
    lon           DOUBLE PRECISION,
    lat           DOUBLE PRECISION,
    name          VARCHAR(255),
    phone_number  VARCHAR(255),
    update_date   TIMESTAMP WITHOUT TIME ZONE,
    city_location VARCHAR(255),
    city_id       BIGINT,
    CONSTRAINT pk_local_places_lift_gates PRIMARY KEY (gates_id)
);

CREATE TABLE point
(
    id      UUID NOT NULL,
    stop_id BIGINT,
    geom    BYTEA,
    CONSTRAINT pk_point PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE route
(
    id                       BIGINT NOT NULL,
    name                     VARCHAR(255),
    from_location            VARCHAR(255),
    to_location              VARCHAR(255),
    network                  VARCHAR(255),
    operator                 VARCHAR(255),
    public_transport_version INTEGER,
    ref                      VARCHAR(255),
    route                    VARCHAR(255),
    CONSTRAINT pk_route PRIMARY KEY (id)
);

CREATE TABLE route_stop
(
    id       UUID NOT NULL,
    route_id BIGINT,
    stop_id  BIGINT,
    sequence INTEGER,
    CONSTRAINT pk_route_stop PRIMARY KEY (id)
);

CREATE TABLE stop
(
    id   BIGINT           NOT NULL,
    name VARCHAR(255),
    lat  DOUBLE PRECISION NOT NULL,
    lon  DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_stop PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_user_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE users
(
    id        BIGINT NOT NULL,
    username  VARCHAR(255),
    city      VARCHAR(255),
    region    VARCHAR(255),
    country   VARCHAR(255),
    latitude  DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    password  VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_COUNTRY FOREIGN KEY (country_id) REFERENCES country (country_id);

ALTER TABLE local_places_lift_gates
    ADD CONSTRAINT FK_LOCAL_PLACES_LIFT_GATES_ON_CITY FOREIGN KEY (city_id) REFERENCES city (city_id);

ALTER TABLE route_stop
    ADD CONSTRAINT FK_ROUTE_STOP_ON_ROUTE FOREIGN KEY (route_id) REFERENCES route (id);

ALTER TABLE route_stop
    ADD CONSTRAINT FK_ROUTE_STOP_ON_STOP FOREIGN KEY (stop_id) REFERENCES stop (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_employee FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (role_id) REFERENCES roles (id);

DROP TABLE planet_osm_line CASCADE;

DROP TABLE planet_osm_point CASCADE;

DROP TABLE planet_osm_polygon CASCADE;

DROP TABLE planet_osm_roads CASCADE;

DROP TABLE power_lines CASCADE;

DROP TABLE spatial_ref_sys CASCADE;